import type { Complexity, Prisma } from "@prisma/client";

export type IntakeQuestion = {
  id: string;
  prompt: string;
  required: boolean;
  type: "choice" | "text" | "upload";
  options?: { value: string; label: string }[];
};

type ServiceSeed = {
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  includedScope: string[];
  excludedScope: string[];
  requiredInformation: string[];
  requiredAccess: string[];
  requiredAttachments: string[];
  intakeQuestions: IntakeQuestion[];
  priceCents: number;
  priceFrom?: boolean;
  complexity: Complexity;
  slaLabel: string;
  slaHours: number;
  isPopular?: boolean;
  diagnosticEligible?: boolean;
  category: string;
  problem?: {
    slug: string;
    title: string;
    h1: string;
    problem: string;
    commonCauses: string[];
    whatWeCheck: string[];
    whatWeCanFix: string[];
    faqs: { q: string; a: string }[];
  };
};

const defaultExcluded = [
  "Marketplace policy decisions we cannot control",
  "Guaranteed reinstatement or approval",
  "Ongoing advertising management",
  "Permanent account credentials or password sharing",
];

const skuQuestion: IntakeQuestion = {
  id: "affected_count",
  prompt: "How many products are affected?",
  required: true,
  type: "choice",
  options: [
    { value: "1-10", label: "1–10" },
    { value: "11-50", label: "11–50" },
    { value: "51-500", label: "51–500" },
    { value: "500+", label: "500+" },
  ],
};

const errorQuestion: IntakeQuestion = {
  id: "error_message",
  prompt: "Do you have an error message?",
  required: false,
  type: "choice",
  options: [
    { value: "yes", label: "Yes" },
    { value: "no", label: "No" },
  ],
};

const uploadQuestion: IntakeQuestion = {
  id: "evidence",
  prompt: "Upload a screenshot or report (optional).",
  required: false,
  type: "upload",
};

function svc(
  partial: Omit<
    ServiceSeed,
    "includedScope" | "excludedScope" | "intakeQuestions" | "requiredAccess" | "requiredAttachments"
  > &
    Partial<
      Pick<ServiceSeed, "includedScope" | "excludedScope" | "intakeQuestions" | "requiredAccess" | "requiredAttachments">
    >,
): ServiceSeed {
  return {
    includedScope: [
      "Issue diagnosis against the selected platform",
      "Recommended fix plan with clearly defined scope",
      "Implementation of in-scope corrections",
      "Verification of the changes we made",
      "Written resolution report",
    ],
    excludedScope: defaultExcluded,
    requiredAccess: ["Scoped collaborator or temporary access when required to implement the fix"],
    requiredAttachments: [],
    intakeQuestions: [skuQuestion, errorQuestion, uploadQuestion],
    ...partial,
  };
}

export const platforms = [
  {
    slug: "amazon",
    name: "Amazon",
    shortName: "Amazon",
    description: "Seller Central listing, catalog, feed, and suppression issues.",
    accent: "#FF9900",
    sortOrder: 1,
    categories: [
      { slug: "listings", name: "Listings" },
      { slug: "catalog", name: "Catalog" },
      { slug: "feeds", name: "Feeds" },
      { slug: "diagnostics", name: "Diagnostics" },
    ],
  },
  {
    slug: "walmart",
    name: "Walmart",
    shortName: "Walmart",
    description: "Walmart Marketplace publishing, item setup, catalog, and feed issues.",
    accent: "#0071DC",
    sortOrder: 2,
    categories: [
      { slug: "publishing", name: "Publishing" },
      { slug: "catalog", name: "Catalog" },
      { slug: "feeds", name: "Feeds" },
      { slug: "diagnostics", name: "Diagnostics" },
    ],
  },
  {
    slug: "shopify",
    name: "Shopify",
    shortName: "Shopify",
    description: "Product, variant, theme, feed, and integration issues.",
    accent: "#96BF48",
    sortOrder: 3,
    categories: [
      { slug: "catalog", name: "Catalog" },
      { slug: "storefront", name: "Storefront" },
      { slug: "integrations", name: "Integrations" },
      { slug: "diagnostics", name: "Diagnostics" },
    ],
  },
  {
    slug: "google-merchant-center",
    name: "Google Merchant Center",
    shortName: "Google",
    description: "Disapprovals, feed errors, identifiers, and visibility issues.",
    accent: "#4285F4",
    sortOrder: 4,
    categories: [
      { slug: "disapprovals", name: "Disapprovals" },
      { slug: "feeds", name: "Feeds" },
      { slug: "diagnostics", name: "Diagnostics" },
    ],
  },
  {
    slug: "tiktok-shop",
    name: "TikTok Shop",
    shortName: "TikTok Shop",
    description: "Product rejection, catalog, feed, and compliance issues.",
    accent: "#111111",
    sortOrder: 5,
    categories: [
      { slug: "publishing", name: "Publishing" },
      { slug: "catalog", name: "Catalog" },
      { slug: "diagnostics", name: "Diagnostics" },
    ],
  },
] as const;

export const servicesByPlatform: Record<string, ServiceSeed[]> = {
  amazon: [
    svc({
      slug: "amazon-listing-suppression",
      name: "Amazon Listing Suppression Fix",
      shortDescription: "Reactivate suppressed or inactive Amazon listings.",
      description:
        "We'll diagnose why the listing is suppressed, identify the likely root cause, and implement the appropriate in-scope corrections. Marketplace approval is subject to Amazon systems and policies.",
      requiredInformation: ["ASIN or SKU", "Suppression notice or screenshot", "Number of affected listings"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      isPopular: true,
      category: "listings",
      problem: {
        slug: "amazon-listing-suppressed",
        title: "Amazon listing suppressed",
        h1: "Amazon Listing Suppressed?",
        problem:
          "A suppressed Amazon listing is not available for purchase. Buyers cannot find or buy it until the suppression reason is addressed.",
        commonCauses: [
          "Missing or invalid product attributes",
          "Image or content quality issues",
          "Compliance or gated-category requirements",
          "Catalog mismatch against the Amazon catalog",
        ],
        whatWeCheck: ["Suppression reason codes", "Catalog identity", "Required attributes", "Listing quality signals"],
        whatWeCanFix: ["Attribute and content corrections", "Catalog alignment", "Submission of the corrected listing data"],
        faqs: [
          {
            q: "Can you guarantee Amazon will unsuppress the listing?",
            a: "No. We implement the recommended correction and verify our changes. Amazon's systems and policies determine final availability.",
          },
        ],
      },
    }),
    svc({
      slug: "amazon-listing-not-showing",
      name: "Amazon Listing Not Showing",
      shortDescription: "Find why a listing is missing from search or the detail page.",
      description:
        "We'll investigate indexing, catalog, and offer visibility issues that can keep a listing from showing.",
      requiredInformation: ["ASIN or SKU", "What you expected to see", "Marketplace"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "listings",
      problem: {
        slug: "amazon-listing-not-showing",
        title: "Amazon listing not showing",
        h1: "Amazon Listing Not Showing?",
        problem: "The listing exists in Seller Central but customers cannot find it in search or on the product page.",
        commonCauses: ["Indexing delays", "Offer not buyable", "Catalog relationship issues", "Search suppression"],
        whatWeCheck: ["Offer status", "Catalog mapping", "Search indexing signals", "Buy box eligibility"],
        whatWeCanFix: ["Offer and catalog corrections that are in our control"],
        faqs: [
          {
            q: "Is this the same as suppression?",
            a: "Not always. A listing can be active but still fail to show because of indexing, catalog, or offer issues.",
          },
        ],
      },
    }),
    svc({
      slug: "amazon-variation-fix",
      name: "Amazon Variation Fix",
      shortDescription: "Repair parent-child variation relationships.",
      description: "We'll diagnose broken variation families and correct parent/child relationships where possible.",
      requiredInformation: ["Parent ASIN", "Child ASINs/SKUs", "Intended variation theme"],
      priceCents: 19900,
      complexity: "QUICK",
      slaLabel: "24 hours",
      slaHours: 24,
      category: "catalog",
      problem: {
        slug: "amazon-variation-not-working",
        title: "Amazon variation not working",
        h1: "Amazon Variation Not Working?",
        problem: "Size, color, or other variants are split, missing, or not selectable on the product page.",
        commonCauses: ["Incorrect variation theme", "Orphaned child SKUs", "Catalog conflicts"],
        whatWeCheck: ["Parent/child relationships", "Variation theme", "SKU-level attributes"],
        whatWeCanFix: ["Variation family structure and related attributes"],
        faqs: [{ q: "Do you merge duplicate catalog records?", a: "When Amazon allows it and it is in scope, yes. Some catalog merges require Amazon catalog action." }],
      },
    }),
    svc({
      slug: "amazon-catalog-fix",
      name: "Amazon Catalog Fix",
      shortDescription: "Correct catalog identity, matching, and contribution issues.",
      description: "We'll diagnose catalog matching problems and implement allowed catalog corrections.",
      requiredInformation: ["ASIN", "UPC/EAN/GTIN if available", "Product identifiers"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "catalog",
    }),
    svc({
      slug: "amazon-feed-flat-file-fix",
      name: "Amazon Feed / Flat File Fix",
      shortDescription: "Repair feed or flat-file errors blocking listing updates.",
      description: "We'll review error reports, correct templates, and resubmit in-scope feed data.",
      requiredInformation: ["Error report", "Feed type", "Affected SKUs"],
      requiredAttachments: ["Processing report or error CSV"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "feeds",
    }),
    svc({
      slug: "amazon-product-inactive",
      name: "Amazon Product Inactive Issue",
      shortDescription: "Diagnose and correct inactive offer or listing status.",
      description: "We'll identify why the offer is inactive and apply the appropriate listing or offer corrections.",
      requiredInformation: ["SKU", "Inactive reason if shown"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "listings",
    }),
    svc({
      slug: "amazon-attribute-issue",
      name: "Amazon Attribute Issue",
      shortDescription: "Fix missing or invalid required attributes.",
      description: "We'll map required attributes and correct values that block listing quality or completeness.",
      requiredInformation: ["ASIN/SKU", "Attribute warnings"],
      priceCents: 19900,
      complexity: "QUICK",
      slaLabel: "24 hours",
      slaHours: 24,
      category: "listings",
    }),
    svc({
      slug: "amazon-browse-node-category",
      name: "Amazon Browse Node / Category Issue",
      shortDescription: "Correct browse node or category placement problems.",
      description: "We'll review category placement and apply allowed browse node corrections.",
      requiredInformation: ["ASIN", "Current and intended category"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "catalog",
    }),
    svc({
      slug: "amazon-bulk-listing-cleanup",
      name: "Amazon Bulk Listing Cleanup",
      shortDescription: "Clean up large listing sets with systematic errors.",
      description: "We'll scope a bulk cleanup, correct repeating defects, and verify a sample plus remaining records.",
      requiredInformation: ["SKU count", "Error report", "Priority SKUs"],
      priceCents: 49900,
      priceFrom: true,
      complexity: "COMPLEX",
      slaLabel: "3–5 days",
      slaHours: 120,
      category: "listings",
    }),
    svc({
      slug: "amazon-product-compliance-diagnostic",
      name: "Amazon Product Compliance Diagnostic",
      shortDescription: "Identify likely compliance blockers before a full fix.",
      description: "A diagnostic review of compliance signals. The diagnostic fee can be credited toward the recommended resolution when enabled.",
      requiredInformation: ["ASIN", "Compliance notice"],
      priceCents: 14900,
      complexity: "DIAGNOSTIC",
      slaLabel: "24 hours",
      slaHours: 24,
      diagnosticEligible: true,
      category: "diagnostics",
    }),
    svc({
      slug: "amazon-catalog-diagnostic",
      name: "Amazon Catalog Diagnostic",
      shortDescription: "Determine the catalog issue before implementation.",
      description: "We'll inspect catalog identity and matching, then recommend the next resolution.",
      requiredInformation: ["ASIN", "Identifiers"],
      priceCents: 14900,
      complexity: "DIAGNOSTIC",
      slaLabel: "24 hours",
      slaHours: 24,
      diagnosticEligible: true,
      category: "diagnostics",
    }),
    svc({
      slug: "amazon-account-listing-assessment",
      name: "Amazon Account / Listing Issue Assessment",
      shortDescription: "A structured assessment when the issue is unclear.",
      description: "We'll review the symptoms, isolate the likely issue category, and recommend a resolution.",
      requiredInformation: ["What you are seeing", "Any Seller Central alerts"],
      priceCents: 14900,
      complexity: "DIAGNOSTIC",
      slaLabel: "24 hours",
      slaHours: 24,
      diagnosticEligible: true,
      category: "diagnostics",
    }),
  ],
  walmart: [
    svc({
      slug: "walmart-product-not-publishing",
      name: "Walmart Product Not Publishing",
      shortDescription: "Unblock products that will not publish to Walmart.",
      description:
        "We'll diagnose item setup, attribute, and feed issues that commonly prevent Walmart products from publishing. Final live status is subject to Walmart systems and policies.",
      requiredInformation: ["Item ID or SKU", "Error or unpublished status", "Number of affected products"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      isPopular: true,
      category: "publishing",
      intakeQuestions: [
        skuQuestion,
        {
          id: "symptom",
          prompt: "What are you seeing?",
          required: true,
          type: "choice",
          options: [
            { value: "unpublished", label: "Unpublished" },
            { value: "error", label: "Error" },
            { value: "rejected", label: "Rejected" },
            { value: "missing", label: "Missing" },
            { value: "other", label: "Other" },
          ],
        },
        errorQuestion,
        uploadQuestion,
        {
          id: "item_id",
          prompt: "What is your Walmart Item ID/SKU?",
          required: false,
          type: "text",
        },
      ],
      problem: {
        slug: "walmart-product-not-publishing",
        title: "Walmart product not publishing",
        h1: "Walmart Product Not Publishing?",
        problem: "Products sit in unpublished, error, or rejected states and never become shoppable.",
        commonCauses: ["Invalid attribute mapping", "Item setup conflicts", "Feed schema errors", "Identifier issues"],
        whatWeCheck: ["Item setup", "Required attributes", "Feed responses", "SKU-level errors"],
        whatWeCanFix: ["Item setup and attribute corrections", "Feed/resubmission of in-scope records"],
        faqs: [
          {
            q: "Will Walmart automatically approve the product after your fix?",
            a: "Not necessarily. We correct the likely setup issue and verify our submission. Walmart determines whether the item goes live.",
          },
        ],
      },
    }),
    svc({
      slug: "walmart-product-unpublished",
      name: "Walmart Product Unpublished",
      shortDescription: "Investigate products that were live and then unpublished.",
      description: "We'll identify why previously live items unpublished and apply in-scope corrections.",
      requiredInformation: ["Item ID", "When it unpublished", "Any notices"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "publishing",
    }),
    svc({
      slug: "walmart-item-setup-fix",
      name: "Walmart Item Setup Fix",
      shortDescription: "Correct item setup configuration blocking listings.",
      description: "We'll review item setup fields and correct mapping or configuration errors.",
      requiredInformation: ["SKU", "Setup type", "Error details"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "publishing",
      problem: {
        slug: "walmart-item-setup-error",
        title: "Walmart item setup error",
        h1: "Walmart Item Setup Error?",
        problem: "Item setup fails validation, so the product never reaches a publishable state.",
        commonCauses: ["Category-specific attributes", "GTIN conflicts", "Offer configuration"],
        whatWeCheck: ["Setup payload", "Attribute requirements", "Identifier uniqueness"],
        whatWeCanFix: ["Item setup data that is under seller control"],
        faqs: [{ q: "Do you need Seller Center access?", a: "Often yes, using scoped collaborator access. We do not ask for passwords when avoidable." }],
      },
    }),
    svc({
      slug: "walmart-feed-fix",
      name: "Walmart Feed Fix",
      shortDescription: "Repair Walmart inventory or item feed errors.",
      description: "We'll interpret feed error files and correct the schema or values blocking ingestion.",
      requiredInformation: ["Feed type", "Error file"],
      requiredAttachments: ["Feed error report"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "feeds",
    }),
    svc({
      slug: "walmart-catalog-fix",
      name: "Walmart Catalog Fix",
      shortDescription: "Resolve catalog matching and item identity issues.",
      description: "We'll diagnose catalog conflicts and apply allowed identity corrections.",
      requiredInformation: ["GTIN", "SKU", "Product title"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "catalog",
    }),
    svc({
      slug: "walmart-attribute-fix",
      name: "Walmart Attribute Fix",
      shortDescription: "Correct invalid or missing Walmart attributes.",
      description: "We'll map required attributes for the item type and correct invalid values.",
      requiredInformation: ["SKU", "Attribute errors"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "catalog",
    }),
    svc({
      slug: "walmart-sku-publishing-issue",
      name: "Walmart SKU Publishing Issue",
      shortDescription: "Fix SKU-level publishing failures.",
      description: "We'll isolate SKU-specific publishing failures and correct the blocking fields.",
      requiredInformation: ["SKU list", "Error codes"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "publishing",
    }),
    svc({
      slug: "walmart-product-content-issue",
      name: "Walmart Product Content Issue",
      shortDescription: "Correct content quality or completeness issues.",
      description: "We'll review title, images, and content fields that prevent a complete item.",
      requiredInformation: ["SKU", "Content warnings"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "catalog",
    }),
    svc({
      slug: "walmart-bulk-catalog-cleanup",
      name: "Walmart Bulk Catalog Cleanup",
      shortDescription: "Clean a large unpublished or error catalog.",
      description: "We'll scope repeating defects across a catalog and apply a structured cleanup.",
      requiredInformation: ["SKU count", "Item report"],
      priceCents: 49900,
      priceFrom: true,
      complexity: "COMPLEX",
      slaLabel: "3–5 days",
      slaHours: 120,
      category: "catalog",
    }),
    svc({
      slug: "walmart-diagnostic",
      name: "Walmart Diagnostic",
      shortDescription: "Identify the publishing or catalog issue before a full fix.",
      description: "A diagnostic review. When enabled, this fee can be credited toward the recommended resolution.",
      requiredInformation: ["What you are seeing", "Item report if available"],
      priceCents: 14900,
      complexity: "DIAGNOSTIC",
      slaLabel: "24 hours",
      slaHours: 24,
      diagnosticEligible: true,
      category: "diagnostics",
    }),
  ],
  shopify: [
    svc({
      slug: "shopify-variant-fix",
      name: "Shopify Variant Fix",
      shortDescription: "Repair broken product variants and options.",
      description: "We'll diagnose variant option, SKU, and inventory issues and correct the product structure.",
      requiredInformation: ["Product URL or ID", "What's broken about the variants"],
      priceCents: 19900,
      complexity: "QUICK",
      slaLabel: "24 hours",
      slaHours: 24,
      isPopular: true,
      category: "catalog",
      problem: {
        slug: "shopify-variant-not-working",
        title: "Shopify variant not working",
        h1: "Shopify Variant Not Working?",
        problem: "Customers cannot select the right size, color, or option, or variants show the wrong price or inventory.",
        commonCauses: ["Option value mismatches", "App conflicts", "Theme variant rendering", "Duplicated SKUs"],
        whatWeCheck: ["Product JSON", "Theme rendering", "Apps touching variants", "Inventory links"],
        whatWeCanFix: ["Product/variant data and common theme or app configuration issues"],
        faqs: [{ q: "Do you redesign the theme?", a: "No. Theme work in this service is limited to variant-related fixes, not a redesign." }],
      },
    }),
    svc({
      slug: "shopify-product-issue",
      name: "Shopify Product Issue",
      shortDescription: "Fix product data, publishing, or display problems.",
      description: "We'll inspect product records and storefront display to correct the issue in scope.",
      requiredInformation: ["Product URL", "Expected vs actual behavior"],
      priceCents: 19900,
      complexity: "QUICK",
      slaLabel: "24 hours",
      slaHours: 24,
      category: "catalog",
    }),
    svc({
      slug: "shopify-collection-issue",
      name: "Shopify Collection Issue",
      shortDescription: "Repair collection rules, merchandising, or missing products.",
      description: "We'll correct automated or manual collection configuration causing missing or extra products.",
      requiredInformation: ["Collection URL", "What's wrong"],
      priceCents: 19900,
      complexity: "QUICK",
      slaLabel: "24 hours",
      slaHours: 24,
      category: "catalog",
    }),
    svc({
      slug: "shopify-theme-issue",
      name: "Shopify Theme Issue",
      shortDescription: "Diagnose and fix a specific theme defect.",
      description: "We'll isolate a theme defect affecting products or checkout-adjacent UX and apply a scoped fix.",
      requiredInformation: ["Theme name", "Page URL", "Screenshot"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "storefront",
    }),
    svc({
      slug: "shopify-app-integration-issue",
      name: "Shopify App / Integration Issue",
      shortDescription: "Resolve a broken app or integration affecting products.",
      description: "We'll identify conflicting apps or integration errors and apply a scoped correction.",
      requiredInformation: ["App name", "Error or unexpected behavior"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "integrations",
    }),
    svc({
      slug: "shopify-inventory-sync-issue",
      name: "Shopify Inventory Sync Issue",
      shortDescription: "Fix inventory mismatch between Shopify and a connected channel.",
      description: "We'll trace inventory locations and sync paths, then correct configuration in scope.",
      requiredInformation: ["SKU", "Source of truth", "Connected channels"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "integrations",
    }),
    svc({
      slug: "shopify-product-feed-issue",
      name: "Shopify Product Feed Issue",
      shortDescription: "Repair product feeds leaving Shopify for ads or marketplaces.",
      description: "We'll inspect the feed app/source and correct mapping or filter issues.",
      requiredInformation: ["Feed destination", "Error examples"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "integrations",
    }),
    svc({
      slug: "shopify-tracking-issue",
      name: "Shopify Tracking Issue",
      shortDescription: "Fix missing conversion or pixel tracking.",
      description: "We'll verify pixels and checkout tracking configuration for a scoped tracking defect.",
      requiredInformation: ["Pixels in use", "What's not firing"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "integrations",
    }),
    svc({
      slug: "shopify-conversion-diagnostic",
      name: "Shopify Conversion Diagnostic",
      shortDescription: "Identify likely conversion blockers on a product or checkout path.",
      description: "A diagnostic of conversion-related defects. Does not include a full CRO program.",
      requiredInformation: ["Store URL", "What you observed"],
      priceCents: 14900,
      complexity: "DIAGNOSTIC",
      slaLabel: "24 hours",
      slaHours: 24,
      diagnosticEligible: true,
      category: "diagnostics",
    }),
    svc({
      slug: "shopify-technical-diagnostic",
      name: "Shopify Technical Diagnostic",
      shortDescription: "A technical assessment when the Shopify issue is unclear.",
      description: "We'll isolate the likely technical cause and recommend a resolution.",
      requiredInformation: ["Store URL", "Symptoms"],
      priceCents: 14900,
      complexity: "DIAGNOSTIC",
      slaLabel: "24 hours",
      slaHours: 24,
      diagnosticEligible: true,
      category: "diagnostics",
    }),
  ],
  "google-merchant-center": [
    svc({
      slug: "google-merchant-product-disapproval",
      name: "Product Disapproval Fix",
      shortDescription: "Address Google Merchant Center product disapprovals.",
      description:
        "We'll diagnose disapproval reasons and implement in-scope feed or landing-page corrections. Google determines whether products are approved.",
      requiredInformation: ["Merchant Center ID or screenshot", "Disapproval reason", "Affected item IDs"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      isPopular: true,
      category: "disapprovals",
      problem: {
        slug: "google-merchant-product-disapproved",
        title: "Google Merchant product disapproved",
        h1: "Google Merchant Product Disapproved?",
        problem: "Products are disapproved in Merchant Center and cannot serve in free listings or ads until the reason is addressed.",
        commonCauses: ["Mismatched price or availability", "Landing page issues", "Identifier problems", "Policy flags"],
        whatWeCheck: ["Disapproval codes", "Feed vs landing page", "Identifiers", "Policy-sensitive fields"],
        whatWeCanFix: ["Feed and on-page corrections under your control"],
        faqs: [
          {
            q: "Can you guarantee Google will approve the products?",
            a: "No. We implement the recommended corrections and verify our changes. Google's systems and policies decide approval.",
          },
        ],
      },
    }),
    svc({
      slug: "google-merchant-feed-error",
      name: "Feed Error Fix",
      shortDescription: "Repair Merchant Center feed processing errors.",
      description: "We'll correct schema, formatting, and required-field errors in the product feed.",
      requiredInformation: ["Feed type", "Error report"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "feeds",
    }),
    svc({
      slug: "google-merchant-price-mismatch",
      name: "Price Mismatch Fix",
      shortDescription: "Resolve price mismatches between feed and landing page.",
      description: "We'll locate the mismatch source and correct feed or page price data in scope.",
      requiredInformation: ["Example item IDs", "Currency and country"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "disapprovals",
    }),
    svc({
      slug: "google-merchant-gtin-identifier",
      name: "GTIN / Identifier Issue",
      shortDescription: "Fix GTIN, MPN, or brand identifier problems.",
      description: "We'll correct identifier fields that cause warnings or disapprovals.",
      requiredInformation: ["Item IDs", "Current identifiers"],
      priceCents: 19900,
      complexity: "QUICK",
      slaLabel: "24 hours",
      slaHours: 24,
      category: "feeds",
    }),
    svc({
      slug: "google-merchant-product-not-showing",
      name: "Product Not Showing",
      shortDescription: "Investigate products that are approved but not showing.",
      description: "We'll check eligibility, feed, and destination settings that affect visibility.",
      requiredInformation: ["Item IDs", "Destination (free listings/ads)"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "disapprovals",
    }),
    svc({
      slug: "google-merchant-account-diagnostic",
      name: "Account Diagnostic",
      shortDescription: "Assess account-level Merchant Center issues.",
      description: "A diagnostic of account-level warnings, suspensions, or setup gaps.",
      requiredInformation: ["Account symptoms", "Screenshots"],
      priceCents: 14900,
      complexity: "DIAGNOSTIC",
      slaLabel: "24 hours",
      slaHours: 24,
      diagnosticEligible: true,
      category: "diagnostics",
    }),
    svc({
      slug: "google-merchant-feed-diagnostic",
      name: "Feed Diagnostic",
      shortDescription: "Diagnose feed health before a full fix.",
      description: "We'll review feed structure and recommend the resolution.",
      requiredInformation: ["Feed source", "Error summary"],
      priceCents: 14900,
      complexity: "DIAGNOSTIC",
      slaLabel: "24 hours",
      slaHours: 24,
      diagnosticEligible: true,
      category: "diagnostics",
    }),
    svc({
      slug: "google-merchant-policy-diagnostic",
      name: "Merchant Center Policy Issue Diagnostic",
      shortDescription: "Review likely policy flags without promising approval.",
      description: "We'll interpret policy-related disapprovals and recommend next steps. We do not guarantee policy outcomes.",
      requiredInformation: ["Policy notice", "Affected products"],
      priceCents: 14900,
      complexity: "DIAGNOSTIC",
      slaLabel: "24 hours",
      slaHours: 24,
      diagnosticEligible: true,
      category: "diagnostics",
    }),
  ],
  "tiktok-shop": [
    svc({
      slug: "tiktok-shop-product-rejection",
      name: "Product Rejection Fix",
      shortDescription: "Address TikTok Shop product rejections.",
      description:
        "We'll diagnose rejection reasons and implement in-scope product data corrections. TikTok Shop determines final acceptance.",
      requiredInformation: ["Product ID", "Rejection reason", "Screenshots"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "publishing",
      problem: {
        slug: "tiktok-shop-product-rejected",
        title: "TikTok Shop product rejected",
        h1: "TikTok Shop Product Rejected?",
        problem: "Products are rejected during review and cannot be sold until the stated issues are addressed.",
        commonCauses: ["Category mismatch", "Prohibited attributes", "Image or title issues", "Compliance requirements"],
        whatWeCheck: ["Rejection codes", "Category mapping", "Required fields", "Media quality"],
        whatWeCanFix: ["Product data and assets under seller control"],
        faqs: [
          {
            q: "Do you guarantee the product will pass review?",
            a: "No. We apply the recommended corrections and verify our submission. TikTok Shop policies decide acceptance.",
          },
        ],
      },
    }),
    svc({
      slug: "tiktok-shop-product-publishing",
      name: "Product Publishing Issue",
      shortDescription: "Unblock products that will not publish on TikTok Shop.",
      description: "We'll isolate publishing blockers and correct in-scope listing data.",
      requiredInformation: ["Product ID", "Status shown"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      isPopular: true,
      category: "publishing",
    }),
    svc({
      slug: "tiktok-shop-catalog-issue",
      name: "Catalog Issue",
      shortDescription: "Fix TikTok Shop catalog structure or matching problems.",
      description: "We'll review catalog organization and correct identity or mapping issues.",
      requiredInformation: ["Catalog source", "What's wrong"],
      priceCents: 29900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      isPopular: true,
      category: "catalog",
    }),
    svc({
      slug: "tiktok-shop-feed-issue",
      name: "Feed Issue",
      shortDescription: "Repair TikTok Shop catalog feed errors.",
      description: "We'll correct feed mapping and required fields that prevent ingestion.",
      requiredInformation: ["Feed source", "Error examples"],
      priceCents: 24900,
      complexity: "STANDARD",
      slaLabel: "24–48 hours",
      slaHours: 48,
      category: "catalog",
    }),
    svc({
      slug: "tiktok-shop-compliance-diagnostic",
      name: "Product Compliance Diagnostic",
      shortDescription: "Identify likely TikTok Shop compliance blockers.",
      description: "A diagnostic review of compliance-related rejections. Outcomes remain subject to TikTok Shop policies.",
      requiredInformation: ["Rejection or compliance notice"],
      priceCents: 14900,
      complexity: "DIAGNOSTIC",
      slaLabel: "24 hours",
      slaHours: 24,
      diagnosticEligible: true,
      category: "diagnostics",
    }),
  ],
};

export const pricingTiers: Prisma.PricingTierCreateInput[] = [
  {
    slug: "quick-resolution",
    name: "Quick Resolution",
    priceCents: 19900,
    description: "For simple, clearly defined issues.",
    complexity: "QUICK",
    sortOrder: 1,
  },
  {
    slug: "standard-resolution",
    name: "Standard Resolution",
    priceCents: 29900,
    description: "Diagnosis + implementation + verification. Most popular.",
    complexity: "STANDARD",
    isMostPopular: true,
    sortOrder: 2,
  },
  {
    slug: "complex-resolution",
    name: "Complex Resolution",
    priceCents: 49900,
    priceFrom: true,
    description: "Multi-SKU, multi-system, or technically complex issues.",
    complexity: "COMPLEX",
    sortOrder: 3,
  },
  {
    slug: "diagnostic",
    name: "Diagnostic",
    priceCents: 14900,
    description: "For customers who do not know what is wrong.",
    complexity: "DIAGNOSTIC",
    sortOrder: 4,
  },
];

export const knowledgeArticles = [
  {
    slug: "how-to-prepare-for-a-resolution",
    title: "How to prepare for a resolution",
    excerpt: "What to gather before you describe the problem so diagnosis is faster.",
    seoTitle: "How to prepare for a resolution | Ecom Resolutions",
    seoDescription: "Screenshots, SKUs, and error reports that help us diagnose marketplace issues faster.",
    body: `Bring the platform name, affected SKUs or item IDs, any error text, and a screenshot of what you are seeing. You do not need to know the root cause.\n\nIf you have an item report, processing report, or Merchant Center disapproval list, attach it. That shortens diagnosis.\n\nNever send passwords. We use scoped collaborator or temporary access when implementation requires it.`,
  },
  {
    slug: "what-a-resolution-report-includes",
    title: "What a resolution report includes",
    excerpt: "The written proof you receive when a case is resolved.",
    seoTitle: "What a resolution report includes | Ecom Resolutions",
    seoDescription: "Problem, root cause, action taken, verification, and prevention notes.",
    body: `When a case is resolved you receive a report covering the problem, root cause, action taken, verification, result, and recommended prevention.\n\nThe report documents what we changed. It does not claim marketplace approval unless that approval was actually verified.`,
  },
];
